# Generated by Django 5.2.13 on 2026-04-15 02:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('setor', models.CharField(max_length=200, verbose_name='Setor')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criterios_tecnicos', models.TextField(help_text='Critérios que a entrega deve satisfazer para ser aprovada.', verbose_name='Critérios técnicos')),
                ('formato_entrega', models.CharField(choices=[('arquivo', 'Arquivo'), ('repositorio', 'Repositório'), ('link', 'Link')], default='repositorio', max_length=15, verbose_name='Formato da entrega')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['projeto', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], default='hard', max_length=5, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ferramentas', models.CharField(help_text='Lista de ferramentas separadas por vírgula.', max_length=500, verbose_name='Ferramentas')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=10, verbose_name='Dificuldade')),
                ('nivel_minimo', models.PositiveIntegerField(default=0, help_text='Nível mínimo do usuário para acessar este projeto.', verbose_name='Nível mínimo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['nivel_minimo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('nivel', models.PositiveIntegerField(default=0, verbose_name='Nível')),
                ('xp_total', models.PositiveIntegerField(default=0, verbose_name='XP Total')),
                ('taxa_sucesso', models.FloatField(default=0.0, help_text='Percentual de entregas aprovadas sobre o total.', verbose_name='Taxa de Sucesso (%)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-xp_total'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', models.FileField(blank=True, null=True, upload_to='entregas/', verbose_name='Arquivo')),
                ('repo_url', models.URLField(blank=True, default='', verbose_name='URL do Repositório')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10, verbose_name='Status')),
                ('feedback_validacao', models.TextField(blank=True, default='', verbose_name='Feedback da Validação')),
                ('xp_ganho', models.PositiveIntegerField(default=0, verbose_name='XP ganho')),
                ('entregue_em', models.DateTimeField(auto_now_add=True, verbose_name='Entregue em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.etapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-entregue_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Bio')),
                ('titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título profissional')),
                ('portfolio_url', models.URLField(blank=True, default='', verbose_name='URL do Portfólio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.projeto', verbose_name='Projeto'),
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('remoto', 'Remoto'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], default='remoto', max_length=12, verbose_name='Tipo')),
                ('localizacao', models.CharField(blank=True, default='', max_length=300, verbose_name='Localização')),
                ('publicada_em', models.DateTimeField(auto_now_add=True, verbose_name='Publicada em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-publicada_em'],
            },
        ),
        migrations.CreateModel(
            name='HabilidadeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(default=1, help_text='Nível de proficiência (1-10).', verbose_name='Nível')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_usuario', to='core.habilidade', verbose_name='Habilidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Habilidade do Usuário',
                'verbose_name_plural': 'Habilidades dos Usuários',
                'unique_together': {('usuario', 'habilidade')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('projeto', 'ordem')},
        ),
        migrations.CreateModel(
            name='RequisitoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_requerido', models.PositiveIntegerField(default=1, help_text='Nível mínimo exigido para a habilidade.', verbose_name='Nível requerido')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_vaga', to='core.habilidade', verbose_name='Habilidade')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='core.vaga', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Requisito de Vaga',
                'verbose_name_plural': 'Requisitos de Vagas',
                'unique_together': {('vaga', 'habilidade')},
            },
        ),
    ]
