# Generated by Django 5.2.13 on 2026-05-30 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se desativado, estudantes não podem se inscrever.', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa responsável por este desafio (opcional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, este usuário representa a empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.PositiveIntegerField(default=1, verbose_name='Nível'),
        ),
    ]
