# Generated by Django 5.2.13 on 2026-05-31 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projeto_ativo_projeto_empresa_usuario_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='descricao_adicional',
            field=models.TextField(blank=True, default='', help_text='Informações adicionais sobre você.', verbose_name='Descrição Adicional'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='instituicao_ensino',
            field=models.CharField(blank=True, default='', help_text='Universidade ou instituição onde estuda.', max_length=300, verbose_name='Instituição de Ensino'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tecnologias',
            field=models.TextField(blank=True, default='', help_text='Tecnologias e linguagens (separadas por vírgula).', verbose_name='Tecnologias'),
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, default='', help_text='URL do site da empresa.', verbose_name='Website')),
                ('tecnologias', models.TextField(blank=True, default='', help_text='Tecnologias utilizadas pela empresa (separadas por vírgula).', verbose_name='Tecnologias')),
                ('area_atuacao', models.CharField(blank=True, default='', help_text='Área principal da empresa (ex: SaaS, Fintech, E-commerce).', max_length=200, verbose_name='Área de Atuação')),
                ('descricao_adicional', models.TextField(blank=True, default='', help_text='Informações adicionais sobre a empresa, cultura, etc.', verbose_name='Descrição Adicional')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfis de Empresas',
            },
        ),
    ]
