# Generated by Django 5.2.13 on 2026-08-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario_descricao_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], db_index=True, default='pendente', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Se desativado, estudantes não podem se inscrever.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='xp_total',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='XP Total'),
        ),
    ]
